config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about', to: 'pages#about'

  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except:[:new] 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            presence: true,
            length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def update
    
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
    
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home

  end
  
  def about
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)

    password = params[:session][:password]

    if user && user.authenticate(password)
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
    
  end
    
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    # p user_params
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end    
  end

  def edit
    @user = User.find(params[:id])
  end
    
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded")
  end
end

app/views/articles/_article.html.erb
<div class="card-columns">
  <% articles_object.each do |article| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= article.title %></h5>
        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
        <small>
        Created By: <%= article.user.username if article.user%>, Created <%= time_ago_in_words(article.created_at)%> ago
        </small>
      </div>
      <div class="card-footer bg-transparent border-light">
        <div class="btn-group d-flex" role="group" aria-label="Actions on Article">
          <%= link_to 'Show', article_path(article), class: "btn btn-primary btn-sm" %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-secondary btn-sm" %>
          <%= link_to 'Delete', article_path(article), class: "btn btn-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
    <ul class="m-0">
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div class="card border-light">
  <div class="card-body">
    <%= form_for @article do |f| %>
      <div class="form-group">
        <%= f.label :title, id: "title"%>
        <%= f.text_field :title, class: "form-control", id: "title"%>
      </div>
      <div class="form-group">
        <%= f.label :description, id: "description"%>
        <%= f.text_area :description, rows:6, class: "form-control", id: "description"%>
      </div>
      
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to "Back to all Articles", articles_path %>
        <%= f.submit class: "btn btn-primary"%>
      </div>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-lg-7 col-md-10 col-sm-12 mx-auto">
    <h1 class="my-3">Edit existing article</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/articles/index.html.erb
<h1 class="my-3">All Articles</h1>
<%= render 'article', articles_object: @articles %>

<div>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-lg-7 col-md-10 col-sm-12 mx-auto">
    <h1 class="my-3">New Article</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="jumbotron my-3">
  <h1 class="display-4"><%= @article.title %></h1>
  <p class="lead"><%= @article.description %></p>
  <hr class="my-4">
  <%= link_to "Back to all Articles", articles_path, class: "btn btn-primary" %>
  <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-secondary" %>
  <%= link_to 'Delete this Article', article_path(@article), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}"%> alert-dismissible fade show mt-2' role="alert">
    <strong>Message: </strong> <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nevigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Alpha Blog', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New Article', new_article_path, class: "nav-link"%>
        </li>
      </ul>
      <span>
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <%= link_to 'Login', login_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Signup', signup_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path,method: :delete,  class: "nav-link"%>
            </li>
          </ul>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nevigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'HOME', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron my-3">
  <h1>Alpha Blog</h1>
  <p class="lead my-4">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <%= link_to 'Sign Up', "#", class: "btn btn-primary btn-lg" %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
    <ul class="m-0">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div class="card border-light">
  <div class="card-body">
    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :username, id: "username"%>
        <%= f.text_field :username, class: "form-control", id: "username"%>
      </div>
      <div class="form-group">
        <%= f.label :email, id: "email"%>
        <%= f.email_field :email, class: "form-control", id: "email"%>
      </div>
      <div class="form-group">
        <%= f.label :password, id: "password"%>
        <%= f.password_field :password, class: "form-control", id: "password"%>
      </div>
      
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to "Back to all Articles", articles_path %>
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary') %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-7 col-md-10 col-sm-12 mx-auto">
    <h1 class="my-3">Update</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="my-4">All Alpha Bloggers</h1>

<ul class="list-unstyled">
  <% @users.each do |user| %>
    <li class="media">
      <%= link_to gravatar_for(user), user_path(user) %>
      <div class="media-body ml-3">
        <h5 class="mt-0 mb-1"><%= link_to user.username, user_path(user) %></h5>
        <small>This blogger created <%= pluralize(user.articles.count, "article") if user.articles %></small>
      </div>
    </li>
    <hr>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-7 col-md-10 col-sm-12 mx-auto">
    <h1 class="my-3">Signup</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center my-4">Welcome to <%= @user.username %>'s page</h1>
<div class="d-flex justify-content-center">
  <%= gravatar_for @user, size: 150 %>
</div>
<h4 class="my-4"><%= @user.username %>'s articles</h4>
<%= render 'articles/article', articles_object: @user.articles %>